---
- name: Install logwatch
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 300
  with_items:
   - logwatch 
   - libdate-manip-perl

 - name: Email logwatch with cron
   cron:
     name: "Weekly logwatch"
     job: logwatch --mailto {{ admin_email }} --output mail --format html --range 'between -7 days and today' 
     special_time: weekly