---
- name: Allow passwordless sudo -- CentOS/RHEL
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Allow passwordless sudo -- Ubuntu/Debian
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'