---
- hosts: alpha.lonix.me
  become: true
  roles:
    - ansible-role-docker
    - { role: ansible-role-rclone, rclone_version: 1.34 }
    - ansible-role-sysdig
    - harden-linux
    - lonix-new
    - ironicbadger
    - alpha.lonix.me
