---
- hosts: all
  become: true
  roles:
    - ansible-role-docker
    - { role: ansible-role-rclone, rclone_version: 1.36 }
    - ansible-role-sysdig
    - harden-linux
    - lonix-new
    - ironicbadger
    - alpha.lonix.me

