---
- hosts: all
  become: true
  roles:
    - ansible-role-docker
#    - { role: hubisan.virtualbox, virtualbox_version: "5.1", virtualbox_install_dkms: yes }
#    - { role: infOpen.vagrant }
    - ansible-role-snapraid
    - memoria-core
    - harden-linux
    - lonix
