# traefik.toml
################################################################
# Global configuration
################################################################
traefikLogsFile = "/log/traefik.log"
accessLogsFile = "/log/access.log"
logLevel = "ERROR"

# InsecureSkipVerify = true
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


################################################################
# Lets Encrypt
################################################################
[acme]
email = "lonixx@gmail.com"
storage = "acme.json"
entryPoint = "https"
onDemand = true
OnHostRule = true

[[acme.domains]]
main = "lonix.me"

################################################################
# Docker configuration backend
################################################################
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "lonix.me"
watch = true
exposedbydefault = true
swarmmode = false

################################################################
# Docker configuration backend
################################################################
[web]
address = ":8080"
ReadOnly = true
  [web.auth.basic]
    users = ["lonix:$apr1$ExF7Gc3o$dT.1tXKrwDJqyP9XxfzY60"]
