---
 - name: Add user - Add all users
   user:
     name={{ item.name }}
     append=yes
     groups={{ item.groups }}
     state=present
     shell=/bin/zsh
   with_items: "{{users}}"
   failed_when: false
   
 - name: Add user - Add all ssh keys
   authorized_key:
     user={{ item.name }}
     key=https://github.com/{{ item.name }}.keys
   with_items: "{{users}}"
