---
- name: ensure os-included packages are up-to-date
  include: os-update.yml
  when: os_update

- name: install basic packages
  include: pkg-install.yml
  when: pkg_install

- name: add backup key to root
  include: add-backup-keys.yml
  when: backup_keys