---
- name: start nfs service
  service:
    name: nfs-kernel-server
    state: started

- name: exportfs
  command: exportfs -ra

- name: restart nfs service
  service:
    name: nfs-kernel-server
    state: restarted
