---

- name: plex container
  docker:
    name: plex
    image: linuxserver/plex
    state: reloaded
    pull: always
    net: host
    volumes:
    - /mnt/nas1/tvshows:/media/series
    - /opt/plex:/config
    - /mnt/storage/movies:/media/movies
    - /mnt/storage/movies-childern:/media/movies-children
    - /mnt/storage/music:/media/music
    - /mnt/nas1/bilder:/media/pictures
    - /mnt/storage/series-archive:/media/series-archive
    - /mnt/storage/series-childern:/media/series-childern
    - /mnt/storage/preroll:/media/preroll
    env:
      PUID: 99
      PGID: 100
      VERSION: latest

- name: plexpy container
  docker:
    pull: always
    name: plexpy
    image: linuxserver/plexpy
    state: reloaded
    net: bridge
    ports:
      - 8181
    volumes:
      - /opt/plexpy:/config
      - /opt/plex/Library/Application Support/Plex Media Server/Logs/:/logs
    env:
      PUID: 99
      PGID: 100
      VIRTUAL_HOST: plexpy.lonix.me
      LETSENCRYPT_HOST: "{{ letsencrypt_hosts }}"
      LETSENCRYPT_EMAIL: lonixx@gmail.com

- name: plexrequest container
  docker:
    pull: always
    name: plexrequests
    image: aptalca/docker-plexrequests
    state: reloaded
    net: bridge
    ports:
     - 3000
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /opt/plexrequests:/config:rw
    env:
      BRANCH: master
      VIRTUAL_HOST: requests.lonix.me
      LETSENCRYPT_HOST: "{{ letsencrypt_hosts }}"
      LETSENCRYPT_EMAIL: lonixx@gmail.com



- name: couchpotato container
  docker:
    pull: always
    name: couchpotato
    image: linuxserver/couchpotato
    state: reloaded
    net: bridge
    ports:
      - 5050
    volumes:
      - /opt/couchpotato:/config
      - /opt/downloads:/downloads
      - /mnt/storage/movies:/movies
    env:
      PUID: 99
      PGID: 100
      VIRTUAL_HOST: film.lonix.me
      LETSENCRYPT_HOST: "{{ letsencrypt_hosts }}"
      LETSENCRYPT_EMAIL: lonixx@gmail.com

- name: nzbhydra
  docker:
    pull: always
    name: nzbhydra
    image: linuxserver/hydra
    state: reloaded
    net: bridge
    ports:
      - 5075
    volumes:
      - /opt/nzbhydra/config:/config
      - /opt/nzbhydra/downloads:/downloads
    env:
      PUID: 99
      PGID: 100
      VIRTUAL_HOST: hydra.lonix.me
      LETSENCRYPT_HOST: "{{ letsencrypt_hosts }}"
      LETSENCRYPT_EMAIL: lonixx@gmail.com



- name: nzbget
  docker:
    pull: always
    name: nzbget
    image: linuxserver/nzbget
    state: reloaded
    net: bridge
    ports:
      - 6789
    volumes:
      - /opt/nzbget:/config
      - /opt/downloads:/downloads

    env:
      PUID: 99
      PGID: 100
      VIRTUAL_HOST: download.lonix.me
      LETSENCRYPT_HOST: "{{ letsencrypt_hosts }}"
      LETSENCRYPT_EMAIL: lonixx@gmail.com

- name: owncloud
  docker: 
    pull: always
    name: owncloud
    image: owncloud:latest
    state: reloaded
    net: bridge
    ports:
      - 80
    volumes:
      - /opt/owncloud:/var/www/html
    env:
      VIRTUAL_HOST: sky.lonix.me
      LETSENCRYPT_HOST: "{{ letsencrypt_hosts }}"
      LETSENCRYPT_EMAIL: lonixx@gmail.com

- name: ghost
  docker:
    pull: always
    name: ghost
    image: ghost
    state: reloaded
    net: bridge
    ports:
     - 2368
    volumes:
     - /opt/ghost:/var/lib/ghost
    env:
      VIRTUAL_HOST: lonix.me
      LETSENCRYPT_HOST: "{{ letsencrypt_hosts }}"
      LETSENCRYPT_EMAIL: lonixx@gmail.com
    
- name: proxy
  docker:
    pull: always
    name: proxy
    image: jwilder/nginx-proxy
    state: reloaded
    net: bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/proxy/cert:/etc/nginx/certs:ro
      - /opt/proxy/vhost.d:/etc/nginx/vhost.d:rw
      - /opt/proxy/html:/usr/share/nginx/html

- name: lets-encrypt
  docker: 
    pull: always
    name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    state: reloaded
    net: bridge
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /opt/proxy/cert:/etc/nginx/certs:rw
    volumes_from:
     - proxy

- name: sonarr
  docker:
    pull: always
    name: sonarr
    image: linuxserver/sonarr
    state: reloaded
    net: bridge
    ports:
      - 8989
    volumes:
      - /opt/sonarr:/config
      - /opt/downloads:/downloads
      - /mnt/nas1/tvshows:/tv
    env:
      PUID: 99
      PGID: 100
      VIRTUAL_HOST: tv.lonix.me
      LETSENCRYPT_HOST: "{{ letsencrypt_hosts }}"
      LETSENCRYPT_EMAIL: lonixx@gmail.com

- name: unifi
  docker:
    pull: always
    name: unifi
    image: rednut/unifi-controller
    state: reloaded
    net: bridge
    ports: 
      - 8443:8443
      - 8080:8080
      - 8880:8880
      - 27117:27117
    volumes: 
     - /opt/unifi:/usr/lib/unifi/data
    env:
     VIRTUAL_PORT: 8443
     VIRTUAL_HOST: unifi.lonix.me
     VIRTUAL_PROTO: https
     LETSENCRYPT_HOST: "{{ letsencrypt_hosts }}"
     LETSENCRYPT_EMAIL: lonixx@gmail.com

