---
 - name: Installing Requirements
   package: name={{item}} state=latest
   with_items:
     - libio-socket-ssl-perl
     - libnet-libidn-perl 
     - libnet-ssleay-perl
     - libdata-validate-ip-perl
     - perl
     - libjson-any-perl

- name: Clone ddclient from git
  sudo: yes
  git: 
    dest: "/root/ddclient" 
    force: yes 
    repo: "https://github.com/wimpunk/ddclient.git"
    update: yes
  register: gitpull

- name: Install ddclient
  sudo: yes
  copy: 
    src: /root/ddclient/ddclient
    dst: /usr/sbin/ddclient
    mode: 755
    owner: root
    remote_src: true

- name: Create /var/cache/ddclient
  sudo: yes
  file:
    path: /var/cache/ddclient
    state: directory

- name: Install ddclient configfile.
  template:
    src: ddclient.conf.j2
    dst: /etc/ddclient/ddclient.conf
    owner: root
    group: root
    mode: 600


