---

 - name: Install rsnapshot
   package: 
     name: rsnapshot
     state: latest

 - name: Copy rsnapshot.conf inplace
   copy: 
     src: etc/rsnapshot.conf
     dest: /etc/rsnapshot.conf
     mode: 644
     owner: root 
     group: root
