---

- include_vars: vault.yml 
- name: clone snapraid-runner
  git:
    repo: https://github.com/Chronial/snapraid-runner.git
    dest: /opt/snapraid-runner

- name: Install snapraid config.
  copy:
    src: etc/snapraid.conf
    dest: /etc/snapraid.conf
    owner: root
    group: root

- name: Install snapraid-runner config.
  template:
    src: snapraid-runner.j2
    dest: /opt/snapraid-runner/snapraid-runner.conf

- name: Add snapraid cron job
  cron:
    user: root
    job: python2 /opt/snapraid-runner/snapraid-runner.py -c /opt/snapraid-runner/snapraid-runner.conf
    name: "Snapraid-runner"
    hour: 08
    minute: 00
   
