---

 - name: create /mnt points
   file:
     dest: "/mnt/{{ item }}"
     state: directory
     owner: nobody
     group: nogroup
     mode: 0777
   with_items: "{{ mounts }}"


 - name: Mount /mnt/disk(s)
   mount:
     name: "{{ item.dst }}"
     src: "{{ item.src }}"
     fstype: "{{ item.fs }}"
     state: mounted
   with_items: "{{ drives }}"


 - name: Mount /mnt/nas
   mount: name="{{ item.dst }}" src="{{ item.host }}:{{ item.src }}"  fstype=nfs state=mounted
   with_items: "{{ drivesnfs }}"

 - name: Mount /mnt/storage
   mount: 
     name: /mnt/storage
     src: /mnt/disk*
     opts: direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs
     fstype: fuse.mergerfs
     state: mounted

 - name: Enable Services
   service:
     name: "{{ item }}"
     enabled: yes
   with_items: 
     - smbd
     - nfs-kernel-server
   notify: 
     - start nfs service
     - start samba service


 - name: Samba Shareing.
   copy:
     src: etc/samba/smb.conf
     dest: /etc/samba/smb.conf
     owner: root
     group: root
   notify:
     - restart samba service


 - name: NFS Shares
   copy:
     src: etc/exports
     dest: /etc/exports
     owner: root
     group: root
   notify:
     - exportfs
     - restart nfs service



