- name: unifi
  docker_container:
    pull: true
    name: unifi
    image: rednut/unifi-controller
    state: started
    network_mode: bridge
    restart_policy: always
    ports:
      - 8443:8443
      - 8080:8080
      - 8880:8880
      - 27117:27117
    volumes:
     - /opt/unifi:/usr/lib/unifi/data
    env:
     VIRTUAL_PORT: 8443
     VIRTUAL_HOST: unifi.lonix.me
     VIRTUAL_PROTO: https
     LETSENCRYPT_HOST: "{{ letsencrypt_hosts }}"
     LETSENCRYPT_EMAIL: lonixx@gmail.com
