---
 - name: Starting\Updating Teamspeak Container
   docker:
     pull: "{{ 'always' if update_containers else 'missing' }}"
     name: teamspeak
     image: linuxserver/gsm-ts3
     state: reloaded
     net: bridge
     ports:
      - 30033:30033
      - 9987:9987/udp
      - 10011:10011
      - 41144:41144
     volumes:
      - /opt/teamspeak:/config:rw
      - /etc/localtime:/etc/localtime:ro

 - name: Starting\Updating Proxy Container
   docker:
    pull: "{{ 'always' if update_containers else 'missing' }}"
    name: proxy
    image: jwilder/nginx-proxy
    docker_user: 911
    state: reloaded
    net: bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/proxy:/etc/nginx/certs
      - /opt/proxy/vhost.d:/etc/nginx/vhost.d:rw

 - name: Starting\Updating Jenkins Container
   docker:
    pull: "{{ 'always' if update_containers else 'missing' }}"
    name: jenkins
    image: jenkins
    state: reloaded
    docker_user: 911
    net: bridge
    ports:
      - 50000:50000
      - 8080
    volumes:
      - /opt/jenkins:/var/jenkins_home
    env:
      VIRTUAL_PORT=8080
      VIRTUAL_HOST=ci.linuxserver.io
      JAVA_OPTS="-Xmx2048m"

 - name: Starting\Updating Owncloud Container
   docker:
    pull: "{{ 'always' if update_containers else 'missing' }}"
    name: owncloud
    image: lsiodev/owncloud
    state: reloaded
    net: bridge
    ports: 443
    volumes:
      - /opt/owncloud/config:/config:rw
      - /opt/owncloud/data:/data:ro
    env:
      TZ=Europe/Paris
      VIRTUAL_PROTO=https
      VIRTUAL_HOST=owncloud.linuxserver.io
      ADVANCED_SCRIPT=true

 - name: Git Pull Slackbridge
   git:
     repo: https://github.com/caktux/Slackbridge
     dest: /opt/slackbridge
   register: git
 
 - name: Updateing Slackbridge image
   docker_image:
     path: /opt/slackbridge/docker
     name: slackbridge
     state: build
   when: git.changed
 
 - name: Starting\Updating Slackbridge Container
   docker:
     name: slackbridge
     image: slackbridge
     state: reloaded
     net: bridge