---
- name: Install docker-py
  pip: 
    name: docker-py
    state: present

- name: Add Docker Repo-Key
  apt_key:
    id: "{{ apt_key_sig }}"
    url: "{{ apt_key_url }}"
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Add Docker Repo
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: yes
    state: present

- name: Install Docker-engine
  apt:
    name: "docker-engine"
    state: "{{ 'latest' if update_docker_package else 'present' }}"
    update_cache: yes
  notify:
    - systemd daemon-reload
    - restart docker service

- name: Start Docker-engine
  service:
    name: docker
    state: started
