---
 - name: Add lsio group to system
   sudo: yes
   group: gid=911  name=lsio  state=present  system=no  

 - name: Add Users to System
   user:
     name={{ item.name }}
     append=yes
     groups={{ item.groups }}
     state={{ item.state }}
     shell=/bin/zsh
     uid={{ item.uid }}
   with_items: "{{users}}"
   failed_when: false

 - name: Add Users ssh keys
   authorized_key:
     user={{ item.name }}
     key=https://github.com/{{ item.name }}.keys
   with_items: "{{ users }}"
   when: item.state == "present"

#Needs to be re-written

 - name: Add users to sudo -- Ubuntu
   user:
      name={{item}}
      append=yes
      groups=sudo
   with_items: "{{sudo}}"
   when: ansible_distribution == 'Ubuntu'

 - name: Add users to Wheel -- CentOS
   user:
      name={{item}}
      append=yes
      groups=wheel
   with_items: "{{sudo}}"
   when: ansible_distribution == 'CentOS'

 - name: Disable sudo Password requirements -- CentOS 
   lineinfile: 
     dest: /etc/sudoers 
     regexp: '^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
     state: present 
   when: ansible_distribution == 'CentOS'

 - name: Disable sudo Password requirements -- Ubuntu
   lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"
   when: ansible_distribution == 'Ubuntu'

 - name: Disallow password ssh
   lineinfile: dest=/etc/ssh/sshd_config
               regexp="^PasswordAuthentication"
               line="PasswordAuthentication no"
               state=present
   notify: Restart ssh 