---
users:
  - {name: lonix, groups: docker}
  - {name: IronicBadger, groups: docker}
  - {name: CHBMB, groups: docker}
  - {name: j0nnymoe, groups: docker}
  - {name: JAGFin1, groups: docker}
  - {name: KodeStar, groups: docker}
  - {name: pecigonzalo, groups: docker}
  - {name: smdion, groups: docker}
  - {name: sparklyballs, groups: docker}
  - {name: Squidly271, groups: docker}
