---

- name: Ensure pip3 is present
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Ensure acd-cli is latest
  pip:
    name: 'git+https://github.com/yadayada/acd_cli.git'
    state: latest
  become: true
