---
- include_vars: vault.yml
  tags: containers
  
- name: Traefik Reverse Proxy
  tags: containers
  docker_container:
    name: traefik
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/acme:/etc/traefik/acme
      - /opt/traefik/traefik.toml:/traefik.toml
    ports:
      - 443:443/tcp
      - 80:80/tcp
      - 9000/tcp
    labels:
      traefik.port: "9000"
    restart_policy: unless-stopped

- name: Resillio Sync
  tags: containers
  docker_container:
    name: sync
    image: resilio/sync
    volumes:
      - /opt/sync:/mnt/sync
      - /mnt/backup:/mnt/mounted_folders/alpha-backup
      - /opt/factorio:/mnt/factorio
    ports:
      - 55555:5555/tcp
    labels:
      traefik.port: "8888"


- name: Datadog Agent
  tags: containers
  docker_container:
    name: Datadog
    image: datadog/docker-dd-agent:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    env:
      API_KEY: "{{ datadog_key }}"
      SD_BACKEND: docker
    labels:
      traefik.enable: false

- name: PostgresSQL
  tags: containers
  docker_container:
    name: postgres
    image: postgres:9
    env:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: quassel
      POSTGRES_PASSWORD: quassel
      POSTGRES_USER: quassel
    volumes:
      - /opt/postgres:/var/lib/postgresql/data
    labels:
      traefik.enable: false

- name: Quassel IRC
  tags: containers
  docker_container:
    name: quassel
    image: linuxserver/quassel-core
    ports:  4242:4242/tcp
    links: postgres:postgres
    volumes:
      - /opt/quassel:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: false
