---
- name: Traefik
  docker_container:
    name: traefik
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/acme:/etc/traefik/acme
      - /opt/traefik/traefik.toml:/traefik.toml
    ports:
      - 443:443/tcp
      - 80:80/tcp
      - 9000:9000/tcp
    restart_policy: unless-stopped
    state: started
  tags: containers

- name: Resillio Sync
  docker_container:
    name: sync
    image: resilio/sync
    volumes:
      - /opt/sync:/mnt/sync
      - /mnt/backup:/mnt/mounted_folders/alpha-backup
      - /opt/factorio:/mnt/factorio
    ports:
      - 55555:5555/tcp
    labels:
      traefik.port: 8888
    state: started
  tags: containers
