---
 - name: Installing Packages
   package: name={{item}} state=latest
   with_items: "{{packages}}"

 - name:  Upgrade OS
   apt:
     upgrade: full
     update_cache: yes
     cache_valid_time: 300
