---
- include_vars: vault.yml 
- name: Install ssmtp config
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf

- name: install ssmtp revaliases file
  copy:
    src: etc/ssmtp/revaliases
    dest: /etc/ssmtp/revaliases
    owner: root
    group: root
