---
- name: start docker service
  service:
    name: docker
    state: started

- name: systemd daemon-reload
  command: systemctl daemon-reload

- name: restart docker service
  service:
    name: docker
    state: restarted

- name: restart ssh
  service: 
    name: ssh 
    state: restarted