---

#Packages to be installed as core
packages:
  - screen
  - git
  - htop
  - sudo
  - nano
  - wget
  - curl
  - bash-completion
  - ncdu
  - openssh-server
  - zsh
  - netcat
  - python-pip
  - samba
  - nfs-kernel-server
  - aptitude

mounts:
  - disk1
  - disk2
  - disk3
  - disk4
  - parity1
  - array

drives:
  - {src: /dev/disk/by-id/ata-ST3000DM001-1CH166_W1F2YYBQ-part1, dst: /mnt/parity1, fs: ext4}
  - {src: /dev/disk/by-id/ata-ST2000DL003-9VT166_5YD5AELE-part1, dst: /mnt/disk1, fs: xfs}
  - {src: /dev/disk/by-id/ata-WDC_WD20EARS-00MVWB0_WD-WCAZA3633963-part1, dst: /mnt/disk2, fs: xfs}
  - {src: /dev/disk/by-id/ata-WDC_WD20EARS-00MVWB0_WD-WCAZA3663919-part1, dst: /mnt/disk3, fs: xfs}
  - {src: /dev/disk/by-id/asdasdas11241r5da, dst: /mnt/disk4, fs: xfs}


snapraid_config_file: /etc/snapraid.conf
mergerfs_version: 2.13.1

