---
#Packages to be installed as core
packages:
  - screen
  - git
  - htop
  - sudo
  - nano
  - wget
  - curl
  - bash-completion
  - ncdu
  - openssh-server
  - zsh
  - netcat
  - python-pip
  - samba
  - nfs-kernel-server
  - aptitude

mounts:
  - disk1
  - disk2
  - disk3
  - parity1
  - storage
  - nas1/tvshows
  - nas1/bilder

drives:
  - {src: /dev/disk/by-id/ata-ST3000DM001-1CH166_W1F2YYBQ-part1, dst: /mnt/parity1, fs: ext4}
  - {src: /dev/disk/by-id/ata-ST2000DL003-9VT166_5YD5AELE-part1, dst: /mnt/disk1, fs: xfs}
  - {src: /dev/disk/by-id/ata-WDC_WD20EARS-00MVWB0_WD-WCAZA3633963-part1, dst: /mnt/disk2, fs: xfs}
  - {src: /dev/disk/by-id/ata-WDC_WD20EARS-00MVWB0_WD-WCAZA3663919-part1, dst: /mnt/disk3, fs: xfs}

drivesnfs:
 - {src: /c/bilder, dst: /mnt/nas1/bilder, host: nas1}
 - {src: /c/tvshows, dst: /mnt/nas1/tvshows, host: nas1}



letsencrypt_hosts: lonix.me,tv.lonix.me,sky.lonix.me,download.lonix.me,hydra.lonix.me,film.lonix.me,plexpy.lonix.me,requests.lonix.me,unifi.lonix.me
snapraid_config_file: /etc/snapraid.conf
mergerfs_version: 2.13.1

