---
 - name: Teamspeak Container
   docker: 
     name: teamspeak
     image: linuxserver/gsm-ts3
     state: started
     ports:
      - 30033:30033
      - 9987:9987/udp
      - 10011:10011
      - 41144:41144
     volumes:
      - /opt/teamspeak:/config:rw
      - /etc/localtime:/etc/localtime:ro

 - name: Proxy Container
   docker:
    name: proxy
    image: jwilder/nginx-proxy
    state: started
    ports:
      - 80:80
      - 443:443 
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro 
      - /opt/proxy:/etc/nginx/certs

 - name: Jenkins Container
   docker:
    name: jenkins
    image: jenkins
    state: started
    ports:
      - 50000:50000
      - 8080
    volumes:
      - /opt/jenkins:/var/jenkins_home
    env:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=ci2.linuxserver.io
      - JAVA_OPTS="-Xmx8192m"